"""Generate knowledge_base/topology/ieee14_grid.md from pandapower's case14.

Provenance rule (plan §2.9): topology facts have a machine-checkable source of
truth (the simulator), so this doc is GENERATED, never hand-edited. Re-run after
any pandapower upgrade. Breakers are a fictional overlay: one per branch,
named BR-<from>-<to> (1-based MATPOWER bus numbers, transformers included).

Run: conda run -n xai python scripts/export_topology.py
"""
from __future__ import annotations

from pathlib import Path

import pandapower as pp
import pandapower.networks as pn

OUT = Path(__file__).resolve().parents[1] / "knowledge_base" / "topology" / "ieee14_grid.md"


def bus_no(net, idx: int) -> int:
    return int(idx) + 1  # pandapower is 0-based; MATPOWER/IEEE numbering is 1-based


def main() -> None:
    net = pn.case14()
    pp.runpp(net)  # solved base case: gives per-branch loading for "normal range" context

    lines = []
    lines.append("# IEEE 14-Bus System — Grid Topology (generated)\n")
    lines.append("> GENERATED by `scripts/export_topology.py` from pandapower `case14`. "
                 "Do not hand-edit — re-run the script.\n")
    lines.append(f"> pandapower version: {pp.__version__}\n")

    lines.append("\n## Buses\n")
    lines.append("| Bus | Name | Nominal kV | In service |")
    lines.append("|---|---|---|---|")
    for i, row in net.bus.sort_index().iterrows():
        lines.append(f"| {bus_no(net, i)} | {row['name']} | {row.vn_kv:.1f} | {row.in_service} |")

    lines.append("\n## Generators / synchronous condensers\n")
    lines.append("| Bus | P (MW) | Type |")
    lines.append("|---|---|---|")
    for _, row in net.gen.iterrows():
        lines.append(f"| {bus_no(net, row.bus)} | {row.p_mw:.1f} | generator/condenser |")
    for _, row in net.ext_grid.iterrows():
        lines.append(f"| {bus_no(net, row.bus)} | slack | external grid (slack bus) |")

    lines.append("\n## Lines (with breakers)\n")
    lines.append("| Line | From bus | To bus | Max current (kA) | Base-case loading (%) | Breaker |")
    lines.append("|---|---|---|---|---|---|")
    for i, row in net.line.sort_index().iterrows():
        f, t = bus_no(net, row.from_bus), bus_no(net, row.to_bus)
        loading = net.res_line.loc[i, "loading_percent"]
        lines.append(f"| L{i} | {f} | {t} | {row.max_i_ka:.3f} | {loading:.1f} | BR-{f}-{t} |")

    lines.append("\n## Transformers (with breakers)\n")
    lines.append("| Trafo | HV bus | LV bus | Rating (MVA) | Base-case loading (%) | Breaker |")
    lines.append("|---|---|---|---|---|---|")
    for i, row in net.trafo.sort_index().iterrows():
        h, l = bus_no(net, row.hv_bus), bus_no(net, row.lv_bus)
        loading = net.res_trafo.loc[i, "loading_percent"]
        lines.append(f"| T{i} | {h} | {l} | {row.sn_mva:.1f} | {loading:.1f} | BR-{h}-{l} |")

    lines.append("\n## Normal operating ranges\n")
    lines.append("- Bus voltage limits: 0.94–1.10 p.u. (generator-regulated buses in "
                 "case14 sit near the upper end by design).")
    lines.append("- Branch loading: alarm above 90 %, violation above 100 % of rating.")
    vmin, vmax = net.res_bus.vm_pu.min(), net.res_bus.vm_pu.max()
    lmax = max(net.res_line.loading_percent.max(), net.res_trafo.loading_percent.max())
    lines.append(f"- Solved base case (this pandapower version): bus voltages in "
                 f"[{vmin:.3f}, {vmax:.3f}] p.u., max branch loading {lmax:.1f} % — "
                 "within limits (verify with scripts/simulate_consequences.py).")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(net.bus)} buses, {len(net.line)} lines, {len(net.trafo)} trafos)")


if __name__ == "__main__":
    main()
